import { v4 as uuidv4 } from 'uuid';

export const initialColumns = [
  // --- UPSTREAM ---
  { id: 'col-up-new', title: '[UP] New', limit: 0, role: 'queue', policy: 'Ideias e requisitos brutos.\n\n• Métrica: Lead Time\n• Sem restrição de WIP.\n\n👉 Quem puxa: N/A\n👉 Quem empurra para a próxima fila: Stakeholders / Clientes' },
  { id: 'col-up-ref-funcional', title: '[UP] Refinamento Funcional', limit: 0, role: 'queue', policy: 'Refinamento de negócio/funcional.\n\n• Métrica: WIP\n\n👉 Quem puxa: Product Owner (PO)\n👉 Quem empurra para a próxima fila: Product Owner (PO)' },
  { id: 'col-up-ref-tecnico', title: '[UP] Refinamento Técnico', limit: 0, role: 'queue', policy: 'Refinamento técnico da solução.\n\n• Métrica: WIP, Tempo em Fila\n\n👉 Quem puxa: Tech Lead / Arquitetos\n👉 Quem empurra para a próxima fila: Tech Lead / Arquitetos' },
  { id: 'col-up-aprovacao-po', title: '[UP] Aprovação PO', limit: 0, role: 'queue', policy: 'Validação e aprovação do PO antes do desenvolvimento.\n\n• Métrica: Throughput\n\n👉 Quem puxa: Product Owner (PO)\n👉 Quem empurra para a próxima fila: Product Owner (PO)' },
  { id: 'col-up-ready', title: '[UP] Pronto para Replenishment', limit: 4, role: 'queue', policy: 'Ponto final do Upstream. Aguardando a Reunião de Replenishment.\n\n• Métrica: Lead Time\n\n👉 Quem puxa: Product Owner (PO)\n👉 Quem empurra para a próxima fila: PO (no Replenishment)' },

  // --- DOWNSTREAM ---
  { id: 'col-down-ready-dev', title: '[DOWN] Pronto para Desenvolvimento', limit: 3, role: 'queue', policy: 'Ponto de Comprometimento (Commitment Point).\n\n• Métrica: WIP, Cycle Time\n\n👉 Quem puxa: N/A (abastecido pelo Replenishment)\n👉 Quem empurra (para DEV): Desenvolvedores' },
  { id: 'col-down-dev', title: '[DOWN] Em Desenvolvimento', limit: 2, role: 'active', policy: 'Fase ativa de desenvolvimento.\n\n👉 Quem puxa: Desenvolvedores\n👉 Quem empurra para a próxima fila: Desenvolvedores' },
  { id: 'col-down-dev-done', title: '[DOWN] Desenvolvimento Finalizado - Dependência', limit: 2, role: 'queue', policy: 'Desenvolvimento concluído, mas bloqueado/aguardando por dependências.\n\n• Métrica: WIP médio\n\n👉 Quem empurra para cá: Desenvolvedores\n👉 Quem puxa para o fluxo: QA' },
  { id: 'col-down-ready-test', title: '[DOWN] Ready to Teste', limit: 2, role: 'queue', policy: 'Pronto para iniciar os testes.\n\n👉 Quem empurra para cá: Desenvolvedores\n👉 Quem puxa (para testes): Analistas de QA' },
  { id: 'col-down-testing', title: '[DOWN] Testando', limit: 1, role: 'active', policy: 'Fase ativa de Validação e Qualidade.\n\n👉 Quem puxa: Analistas de QA\n👉 Quem empurra para a próxima fila: Analistas de QA' },
  { id: 'col-down-ready-homolog', title: '[DOWN] Ready to Homologação', limit: 2, role: 'queue', policy: 'Testes de QA finalizados. Aguardando validação do negócio.\n\n👉 Quem empurra para cá: Analistas de QA\n👉 Quem puxa (para UAT): Product Owner (PO) / Cliente' },
  { id: 'col-down-val-po', title: '[DOWN] Em validação PO', limit: 1, role: 'active', policy: 'Homologação pelo Cliente/PO (User Acceptance Testing).\n\n👉 Quem puxa: Product Owner (PO) / Cliente\n👉 Quem empurra para a próxima fila: Product Owner (PO) / Cliente' },
  { id: 'col-down-homologado', title: '[DOWN] Homologado', limit: 0, role: 'queue', policy: 'Homologação concluída com sucesso.\n\n👉 Quem empurra para cá: Product Owner (PO)\n👉 Quem puxa (para deploy): DevOps / Release Manager' },
  { id: 'col-down-ready-install', title: '[DOWN] Liberado para Instalar', limit: 0, role: 'queue', policy: 'Pronto para entrar na próxima janela de Release.\n\n👉 Quem empurra para cá: DevOps / Release Manager\n👉 Quem puxa para a Produção: Operações / Infraestrutura' },
  { id: 'col-down-done', title: '[DOWN] Done', limit: 0, role: 'completed', policy: 'Ponto de Entrega (Delivery Point).\n\n• Métrica: Throughput\nO relógio de Cycle Time é interrompido.\n\n👉 Quem empurra para cá: Operações / Infraestrutura' }
];

export const initialCards = [
  {
    id: uuidv4(),
    title: 'Configurar Banco de Dados',
    type: 'padrao', // padrao, urgente, data-fixa, intangivel
    effortTotal: { dev: 32, test: 16, uat: 8 },
    effortLeft: { dev: 32, test: 16, uat: 8 },
    columnId: 'col-up-new',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Interface de Login',
    type: 'padrao',
    effortTotal: { dev: 24, test: 8, uat: 16 },
    effortLeft: { dev: 24, test: 8, uat: 16 },
    columnId: 'col-up-new',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Corrigir Bug Crítico de Segurança',
    type: 'urgente',
    effortTotal: { dev: 16, test: 8, uat: 8 },
    effortLeft: { dev: 16, test: 8, uat: 8 },
    columnId: 'col-up-new',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Atualizar Termos de Uso',
    type: 'data-fixa',
    effortTotal: { dev: 8, test: 8, uat: 16 },
    effortLeft: { dev: 8, test: 8, uat: 16 },
    columnId: 'col-up-new',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    dueDate: 5,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Refatorar Módulo de Auth',
    type: 'intangivel',
    effortTotal: { dev: 40, test: 16, uat: 8 },
    effortLeft: { dev: 40, test: 16, uat: 8 },
    columnId: 'col-up-new',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Exportação de Relatórios',
    type: 'padrao',
    effortTotal: { dev: 24, test: 16, uat: 8 },
    effortLeft: { dev: 24, test: 16, uat: 8 },
    columnId: 'col-up-new',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Integração com API de Pagamento',
    type: 'padrao',
    effortTotal: { dev: 48, test: 24, uat: 16 },
    effortLeft: { dev: 48, test: 24, uat: 16 },
    columnId: 'col-up-new',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Filtro de Pesquisa Avançado',
    type: 'padrao',
    effortTotal: { dev: 16, test: 8, uat: 8 },
    effortLeft: { dev: 16, test: 8, uat: 8 },
    columnId: 'col-up-new',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  }
];

export const cardTypeColors = {
  padrao: 'var(--accent-blue)',
  urgente: 'var(--accent-rose)',
  'data-fixa': 'var(--accent-amber)',
  intangivel: 'var(--accent-purple)',
};
