import { v4 as uuidv4 } from 'uuid';

export const initialColumns = [
  { id: 'col-backlog', title: 'Backlog', limit: 0, role: 'queue', policy: 'Ideias e requisitos brutos.\n\n• Entrada: Qualquer stakeholder pode sugerir ideias.\n• Saída: O Product Owner detalha (Definition of Ready) e as prioriza para a próxima seleção.' },
  { id: 'col-selected', title: 'Selecionado (Ready)', limit: 4, role: 'queue', policy: 'Ponto de Comprometimento (Commitment Point).\n\n• Entrada: O PO prioriza os itens do topo do Backlog na Reunião de Replenishment.\n• Saída: Os devs "puxam" o item do topo apenas quando tiverem vaga no seu Limite de WIP.' },
  { id: 'col-dev-doing', title: 'Dev (Fazendo)', limit: 3, role: 'active', policy: 'Fase ativa de desenvolvimento.\n\n• Entrada: Puxado do Ready. Requisitos devem estar 100% claros.\n• Saída: Código finalizado, testes locais criados, e Code Review (PR) aprovado por 1 colega.' },
  { id: 'col-dev-done', title: 'Dev (Feito)', limit: 0, role: 'done', policy: 'Buffer. Aguardando capacidade da Qualidade.\n\n• Entrada: Código foi mergeado na branch de Staging.\n• Saída: O analista de QA "puxa" para teste quando o limite de WIP dele permitir.' },
  { id: 'col-qa-doing', title: 'QA (Fazendo)', limit: 2, role: 'active', policy: 'Fase ativa de Validação e Qualidade.\n\n• Entrada: Puxado do Dev Done.\n• Saída: Testes exploratórios concluídos, sem bugs críticos encontrados e evidências anexadas ao ticket.' },
  { id: 'col-qa-done', title: 'QA (Feito)', limit: 0, role: 'done', policy: 'Buffer. Aguardando aceite de negócios.\n\n• Entrada: QA aplicou o selo técnico de aprovação.\n• Saída: O PO ou Cliente (UAT) puxa o cartão para homologar o valor de negócio entregue.' },
  { id: 'col-uat-doing', title: 'UAT (Fazendo)', limit: 2, role: 'active', policy: 'Homologação pelo Cliente (User Acceptance Testing).\n\n• Entrada: Puxado do QA Done.\n• Saída: Aceite formal do negócio documentado (via sistema ou e-mail).' },
  { id: 'col-uat-done', title: 'UAT (Feito)', limit: 0, role: 'done', policy: 'Buffer. Fila para entrar em Produção.\n\n• Entrada: Aceite formal do cliente recebido.\n• Saída: Janela de Deploy chegou (Release puxada via pipeline).' },
  { id: 'col-deploy', title: 'Implantado (Deploy)', limit: 0, role: 'completed', policy: 'Ponto de Entrega (Delivery Point).\n\n• Entrada: Código publicado com sucesso em produção.\nO relógio do Lead Time é interrompido.' },
];

export const initialCards = [
  {
    id: uuidv4(),
    title: 'Configurar Banco de Dados',
    type: 'padrao', // padrao, urgente, data-fixa, intangivel
    effortTotal: { dev: 32, test: 16, uat: 8 },
    effortLeft: { dev: 32, test: 16, uat: 8 },
    columnId: 'col-backlog',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Interface de Login',
    type: 'padrao',
    effortTotal: { dev: 24, test: 8, uat: 16 },
    effortLeft: { dev: 24, test: 8, uat: 16 },
    columnId: 'col-backlog',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Corrigir Bug Crítico de Segurança',
    type: 'urgente',
    effortTotal: { dev: 16, test: 8, uat: 8 },
    effortLeft: { dev: 16, test: 8, uat: 8 },
    columnId: 'col-backlog',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Atualizar Termos de Uso',
    type: 'data-fixa',
    effortTotal: { dev: 8, test: 8, uat: 16 },
    effortLeft: { dev: 8, test: 8, uat: 16 },
    columnId: 'col-backlog',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    dueDate: 5,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Refatorar Módulo de Auth',
    type: 'intangivel',
    effortTotal: { dev: 40, test: 16, uat: 8 },
    effortLeft: { dev: 40, test: 16, uat: 8 },
    columnId: 'col-backlog',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Exportação de Relatórios',
    type: 'padrao',
    effortTotal: { dev: 24, test: 16, uat: 8 },
    effortLeft: { dev: 24, test: 16, uat: 8 },
    columnId: 'col-backlog',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Integração com API de Pagamento',
    type: 'padrao',
    effortTotal: { dev: 48, test: 24, uat: 16 },
    effortLeft: { dev: 48, test: 24, uat: 16 },
    columnId: 'col-backlog',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  },
  {
    id: uuidv4(),
    title: 'Filtro de Pesquisa Avançado',
    type: 'padrao',
    effortTotal: { dev: 16, test: 8, uat: 8 },
    effortLeft: { dev: 16, test: 8, uat: 8 },
    columnId: 'col-backlog',
    createdAt: 1,
    startedAt: null,
    completedAt: null,
    activeTime: 0,
    waitTime: 0,
    isBlocked: false,
  }
];

export const cardTypeColors = {
  padrao: 'var(--accent-blue)',
  urgente: 'var(--accent-rose)',
  'data-fixa': 'var(--accent-amber)',
  intangivel: 'var(--accent-purple)',
};
